import { marked } from 'marked'

marked.setOptions({ gfm: true, breaks: false })

const PRINT_STYLES = `
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif;
    font-size: 13px;
    line-height: 1.65;
    color: #1a1a1a;
    max-width: 820px;
    margin: 0 auto;
    padding: 48px;
  }
  .doc-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    border-bottom: 2px solid #4f46e5;
    padding-bottom: 14px;
    margin-bottom: 32px;
  }
  .doc-logo {
    font-size: 14px;
    font-weight: 800;
    color: #4f46e5;
    letter-spacing: -0.4px;
  }
  .doc-logo span { color: #818cf8; }
  .doc-meta {
    font-size: 11px;
    color: #6b7280;
    text-align: right;
    line-height: 1.5;
  }
  .doc-meta strong { color: #111; font-size: 13px; font-weight: 700; display: block; }
  .doc-footer {
    margin-top: 48px;
    padding-top: 12px;
    border-top: 1px solid #e5e7eb;
    font-size: 10px;
    color: #9ca3af;
    text-align: center;
  }
  h1 { font-size: 20px; font-weight: 800; color: #111; margin: 24px 0 10px; }
  h2 {
    font-size: 14px;
    font-weight: 700;
    color: #111;
    margin-top: 28px;
    margin-bottom: 10px;
    padding-bottom: 5px;
    border-bottom: 1px solid #e5e7eb;
    text-transform: uppercase;
    letter-spacing: 0.4px;
  }
  h3 { font-size: 13px; font-weight: 600; color: #374151; margin: 14px 0 6px; }
  p { margin-bottom: 10px; color: #374151; }
  ul, ol { margin: 6px 0 10px 20px; }
  li { margin-bottom: 4px; color: #374151; }
  strong { font-weight: 700; color: #111; }
  em { font-style: italic; }
  table {
    border-collapse: collapse;
    width: 100%;
    margin: 12px 0 16px;
    font-size: 12px;
  }
  th {
    background: #f3f4f6;
    font-weight: 600;
    text-align: left;
    padding: 8px 10px;
    border: 1px solid #d1d5db;
    color: #374151;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.3px;
  }
  td {
    padding: 7px 10px;
    border: 1px solid #d1d5db;
    vertical-align: top;
    color: #374151;
  }
  tr:nth-child(even) td { background: #f9fafb; }
  code {
    background: #f3f4f6;
    padding: 1px 5px;
    border-radius: 3px;
    font-size: 11px;
    font-family: 'Courier New', monospace;
    color: #111;
  }
  blockquote {
    border-left: 3px solid #4f46e5;
    margin: 12px 0;
    padding: 6px 14px;
    color: #6b7280;
    background: #f8f7ff;
  }
  hr { border: none; border-top: 1px solid #e5e7eb; margin: 20px 0; }
  @media print {
    body { padding: 0; }
    @page { margin: 16mm 14mm; size: A4; }
    h2 { page-break-after: avoid; }
    table { page-break-inside: avoid; }
  }
`

export function exportMemoAsPDF(memo, companyName) {
  if (!memo) return

  const html = marked.parse(memo)
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  const page = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${companyName} — Investment Memo</title>
  <style>${PRINT_STYLES}</style>
</head>
<body>
  <div class="doc-header">
    <div class="doc-logo">DealScope<span> AI</span></div>
    <div class="doc-meta">
      <strong>${companyName}</strong>
      Investment Memo &middot; ${date}
    </div>
  </div>
  ${html}
  <div class="doc-footer">
    Generated by DealScope AI &middot; ${date} &middot; Confidential &mdash; Not for Distribution
  </div>
</body>
</html>`

  const win = window.open('', '_blank', 'width=920,height=760,scrollbars=yes')
  if (!win) {
    alert('Please allow popups for this site to download the PDF.')
    return
  }
  win.document.write(page)
  win.document.close()
  win.focus()
  // Small delay so styles render before the print dialog opens
  setTimeout(() => win.print(), 450)
}
